// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/tournaments" | "/admin/tournaments/create" | "/login" | "/prototypes" | "/prototypes/athlete-registration" | "/prototypes/court-dispatcher" | "/prototypes/match-scoresheet" | "/prototypes/organizer-draw" | "/prototypes/umpire-scoring" | "/rankings" | "/register" | "/register/organizer" | "/register/partner-accept" | "/scoreboard" | "/scoreboard/court/[courtNumber]" | "/tournaments/[slug]" | "/tournaments/[slug]/register"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin/tournaments": {}
  "/admin/tournaments/create": {}
  "/login": {}
  "/prototypes": {}
  "/prototypes/athlete-registration": {}
  "/prototypes/court-dispatcher": {}
  "/prototypes/match-scoresheet": {}
  "/prototypes/organizer-draw": {}
  "/prototypes/umpire-scoring": {}
  "/rankings": {}
  "/register": {}
  "/register/organizer": {}
  "/register/partner-accept": {}
  "/scoreboard": {}
  "/scoreboard/court/[courtNumber]": { "courtNumber": string; }
  "/tournaments/[slug]": { "slug": string; }
  "/tournaments/[slug]/register": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
