// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/admin/tournaments/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tournaments/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tournaments/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tournaments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/prototypes/athlete-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototypes/athlete-registration">> = Specific
  const handler = {} as typeof import("../../src/app/prototypes/athlete-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/prototypes/court-dispatcher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototypes/court-dispatcher">> = Specific
  const handler = {} as typeof import("../../src/app/prototypes/court-dispatcher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/prototypes/match-scoresheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototypes/match-scoresheet">> = Specific
  const handler = {} as typeof import("../../src/app/prototypes/match-scoresheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/prototypes/organizer-draw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototypes/organizer-draw">> = Specific
  const handler = {} as typeof import("../../src/app/prototypes/organizer-draw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/prototypes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototypes">> = Specific
  const handler = {} as typeof import("../../src/app/prototypes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/prototypes/umpire-scoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototypes/umpire-scoring">> = Specific
  const handler = {} as typeof import("../../src/app/prototypes/umpire-scoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rankings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rankings">> = Specific
  const handler = {} as typeof import("../../src/app/rankings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/organizer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/organizer">> = Specific
  const handler = {} as typeof import("../../src/app/register/organizer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/partner-accept/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/partner-accept">> = Specific
  const handler = {} as typeof import("../../src/app/register/partner-accept/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/scoreboard/court/[courtNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scoreboard/court/[courtNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/scoreboard/court/[courtNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/scoreboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scoreboard">> = Specific
  const handler = {} as typeof import("../../src/app/scoreboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tournaments/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/tournaments/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tournaments/[slug]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/[slug]/register">> = Specific
  const handler = {} as typeof import("../../src/app/tournaments/[slug]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
